global:
  scrape_interval: 60s
remote_write:
  - url: https://prometheus-prod-40-prod-sa-east-1.grafana.net/api/prom/push
    basic_auth:
      username: 3255140
      password: ${GRAFANA_TOKEN}
scrape_configs:
  # --- AMBIENTE DEV ---
  - job_name: 'infra-service-dev'
    metrics_path: '/q/metrics'
    scheme: 'https'
    static_configs:
      - targets: ['petshop-infra-dev.onrender.com']

  # --- AMBIENTE HOMOL/PROD ---
  - job_name: 'infra-service'
    metrics_path: '/q/metrics'
    scheme: 'https'
    static_configs:
      - targets: ['petshop-infra-service.onrender.com']